/**
 * Dimension-composition prompt assembly for the inspiration composer tab.
 * Data is generated by scripts/build-baoyu-compose.mjs from JimLiu/baoyu-skills
 * (baoyu-cover-image skill, MIT license).
 */
import data from './inspiration/data/baoyu-compose.json' with { type: 'json' }

/** Pseudo inspiration source id that switches the view into composer mode. */
export const BAOYU_COMPOSER_SOURCE_ID = 'baoyu-compose'

export interface BaoyuPaletteColor {
  role: string
  name: string
  hex: string
}

export interface BaoyuPalette {
  id: string
  tagline: string
  colors: BaoyuPaletteColor[]
  decorativeHints: string[]
  bestFor: string
  pairs?: { name: string; a: string; b: string; feel: string }[]
}

export interface BaoyuRendering {
  id: string
  tagline: string
  lines: string[]
  texture: string[]
  depth: string[]
  elements: string[]
}

export interface BaoyuType {
  id: string
  description: string
  composition: string
}

export interface BaoyuMood {
  id: string
  application: string
}

export interface BaoyuTextLevel {
  id: string
  area: string
}

export interface BaoyuSelection {
  type: string
  palette: string
  rendering: string
  text: string
  mood: string
  title: string
}

export const BAOYU_TYPES: BaoyuType[] = data.types
export const BAOYU_PALETTES: BaoyuPalette[] = data.palettes
export const BAOYU_RENDERINGS: BaoyuRendering[] = data.renderings
export const BAOYU_TEXT_LEVELS: BaoyuTextLevel[] = data.textLevels
export const BAOYU_MOODS: BaoyuMood[] = data.moods

/** Chinese labels for every dimension option id, shown when the UI language is zh. */
export const BAOYU_LABELS_ZH: Record<string, string> = {
  hero: '主视觉大图', conceptual: '概念抽象', typography: '文字主导', metaphor: '隐喻象征', scene: '氛围场景', minimal: '极简留白',
  warm: '暖色', cool: '冷色', dark: '暗色', earth: '大地色', elegant: '优雅', macaron: '马卡龙', mono: '单色', pastel: '粉彩', retro: '复古', duotone: '双色调', vivid: '高饱和',
  'flat-vector': '扁平矢量', pixel: '像素风', digital: '数字插画', 'hand-drawn': '手绘', painterly: '绘画感', chalk: '粉笔', 'screen-print': '丝网印刷',
  none: '无文字', 'title-only': '仅标题', 'title-subtitle': '标题+副标题', 'text-rich': '丰富文字',
  subtle: '含蓄', balanced: '均衡', bold: '强烈',
}

export const BAOYU_DEFAULT_SELECTION: BaoyuSelection = {
  type: 'metaphor',
  palette: 'warm',
  rendering: 'flat-vector',
  text: 'title-only',
  mood: 'balanced',
  title: '',
}

function palette(id: string): BaoyuPalette | undefined {
  return BAOYU_PALETTES.find(item => item.id === id)
}

function rendering(id: string): BaoyuRendering | undefined {
  return BAOYU_RENDERINGS.find(item => item.id === id)
}

function typeOf(id: string): BaoyuType | undefined {
  return BAOYU_TYPES.find(item => item.id === id)
}

function moodOf(id: string): BaoyuMood | undefined {
  return BAOYU_MOODS.find(item => item.id === id)
}

function textLevel(id: string): BaoyuTextLevel | undefined {
  return BAOYU_TEXT_LEVELS.find(item => item.id === id)
}

/** Assemble the five-dimension selection into one generate_image-ready prompt. */
export function composeBaoyuPrompt(selection: BaoyuSelection): string {
  const chosenType = typeOf(selection.type)
  const chosenPalette = palette(selection.palette)
  const chosenRendering = rendering(selection.rendering)
  const chosenText = textLevel(selection.text)
  const chosenMood = moodOf(selection.mood)
  if (chosenType === undefined || chosenPalette === undefined || chosenRendering === undefined || chosenText === undefined || chosenMood === undefined) {
    throw new Error('invalid-baoyu-selection')
  }
  const title = selection.title.trim()
  if (selection.text !== 'none' && title === '') throw new Error('baoyu-title-required')

  const primary = chosenPalette.colors.filter(color => color.role.startsWith('Primary'))
  const background = chosenPalette.colors.filter(color => color.role.startsWith('Background'))
  const accent = chosenPalette.colors.filter(color => color.role.startsWith('Accent'))
  const swatch = (colors: BaoyuPaletteColor[]): string => colors.map(color => `${color.name} ${color.hex}`).join(', ')

  const textElements =
    selection.text === 'none'
      ? 'No text elements; the full area stays visual.'
      : [
          `Title: "${title}"`,
          ...(selection.text === 'title-subtitle' || selection.text === 'text-rich' ? ['Subtitle: derive one short supporting line from the title'] : []),
          ...(selection.text === 'text-rich' ? ['Tags: derive 2-3 keyword badges from the title'] : []),
        ].join('\n')

  const pairNote = chosenPalette.pairs === undefined ? '' : `\n- Duotone pair: pick ONE dominant two-color pair from ${chosenPalette.pairs.map(pair => `${pair.name} (${pair.a} + ${pair.b})`).join('; ')}`

  return [
    'Cover image.',
    '',
    '# Visual Design',
    `- Type: ${chosenType.id} — ${chosenType.composition}`,
    `- Palette: ${chosenPalette.id} (${chosenPalette.tagline})`,
    `- Rendering: ${chosenRendering.id} — ${chosenRendering.tagline}`,
    `- Text level: ${chosenText.id} (${chosenText.area})`,
    `- Mood: ${chosenMood.id} — ${chosenMood.application}`,
    '',
    '# Text Elements',
    textElements,
    '',
    '# Composition',
    `- Type composition: ${chosenType.composition}`,
    '- Layout: generous whitespace (40-60% breathing room); one dominant focal point with 1-2 supporting elements plus decorative accents; main visual centered or slightly left, reserving the right side for the title when included.',
    `- Decorative: ${chosenPalette.decorativeHints.join('; ')}`,
    '',
    '# Color Scheme',
    `- Primary: ${swatch(primary)}`,
    `- Background: ${swatch(background)}`,
    `- Accent: ${swatch(accent)}${pairNote}`,
    `- Mood adjustment: ${chosenMood.application}`,
    '- Color constraint: Color values (#hex) and color names are rendering guidance only — do NOT display color names, hex codes, or palette labels as visible text in the image.',
    '',
    `# Rendering Notes (${chosenRendering.id})`,
    `- Lines: ${chosenRendering.lines.join('; ')}`,
    `- Texture: ${chosenRendering.texture.join('; ')}`,
    `- Depth: ${chosenRendering.depth.join('; ')}`,
    `- Elements: ${chosenRendering.elements.join('; ')}`,
    '',
    '# Core Principles',
    '- Ample whitespace, highlight the core message, avoid cluttered layouts.',
    '- Simplified silhouettes for any characters — no realistic human faces or bodies.',
    '- Icon-based vocabulary: represent concepts with simple, recognizable icons.',
  ].join('\n')
}

/** Randomize every visual dimension, keeping the current title text. */
export function randomBaoyuSelection(current: BaoyuSelection): BaoyuSelection {
  const pick = <T,>(items: T[]): T => items[Math.floor(Math.random() * items.length)]!
  return {
    type: pick(BAOYU_TYPES).id,
    palette: pick(BAOYU_PALETTES).id,
    rendering: pick(BAOYU_RENDERINGS).id,
    text: pick(BAOYU_TEXT_LEVELS).id,
    mood: pick(BAOYU_MOODS).id,
    title: current.title,
  }
}
